- name: create config
  ansible.builtin.template:
    src: job.xml
    dest: /tmp/job.xml

- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/job.xml') }}"
    name: test
    url: http://172.31.9.180:8080
    user: admin
    password: "{{jenkins_Password}}"