#- name: create config
#  ansible.builtin.template:
#    src: s-job.xml
#    dest: /tmp/s-job.xml
#
#- name: Create a jenkins job using basic authentication
#  community.general.jenkins_job:
#    config: "{{ lookup('file', '/tmp/s-job.xml') }}"
#    name: "{{item.dir}}/{{item.name}} "
#    url: http://172.31.9.180:8080
#    user: admin
#    password: "{{jenkins_Password}}"

- name: Create Config file
  ansible.builtin.template:
    src: s-s-job.xml
    dest: /tmp/s-s-job.xml

- name: Create Job
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/s-s-job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.7.18:8080
    user: admin
    password: "{{jenkins_password}}"